print("This is the information regarding the students")
print("Enter the details of student 1")
Students_name_1=input("Enter the name of Student:")
Roll_student_1=input("Enter the roll of student")
Student_section_1=input("Enter the Section of student:")
Student_course_1=input("Enter the course of student:")
print(Students_name_1)
print(Roll_student_1)
print(Student_section_1)
print(Student_course_1)
print("\n")
print("Enter the details of student 2")
Students_name_2=input("Enter the name of Student:")
Roll_student_2=(input("Enter the Roll of student:"))
Student_section_2=input("Enter the Section of student:")
Student_course_2=input("Enter the course of student:")
print(Students_name_2)
print(Roll_student_2)
print(Student_section_2)
print(Student_course_2)
print("\n")
print("Enter the details of student 3")
Students_name_3=input("Enter the name of Student:")
Roll_student_3=(input("Enter the Roll of student:"))
Student_section_3=input("Enter the Section of student:")
Student_course_3=input("Enter the course of student:")
print(Students_name_3)
print(Roll_student_3)
print(Student_section_3)
print(Student_course_3)
print("\n")
print("Enter the details of student 4")
Students_name_4=input("Enter the name of Student:")
Roll_student_4=(input("Enter the Roll of student:"))
Student_section_4=input("Enter the Section of student:")
Student_course_4=input("Enter the course of student:")
print(Students_name_4)
print(Roll_student_4)
print(Student_section_4)
print(Student_course_4)
